# Generated by Django 5.2.1 on 2025-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In Stock'),
        ),
    ]
