# Generated by Django 5.2.1 on 2025-06-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EApp', '0003_signupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
