# Generated by Django 5.2.1 on 2025-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EApp', '0005_cartitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
