# Generated by Django 5.2.1 on 2025-07-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EApp', '0008_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Processing', max_length=20)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EApp.deliveryaddressmodel')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EApp.paymentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EApp.signupmodel')),
            ],
        ),
    ]
